- name: Create User and Group on AIX
  hosts: all
  gather_facts: True
  
  tasks:
  - name: Encrypt password:
    command: perl -e 'print crypt("password", "salt")'
#    delegate_to: localhost
    register: enc_password
    
  - name: debugging
    debug:
      var=enc_password
        
#  - name: Update password user "{{ user }}" 
#    user: 
#      name: "{{ user }}" 
#      password: "{{ enc_password }}"
#      update_password: always
