- name: Create User and Group on AIX
  hosts: all
  gather_facts: True
  
  tasks:
  - name: add group "{{ user }}" 
    group: 
      name: "{{ user }}" 
      state: present
      
  - name: create user "{{ user }}" 
    user: 
      name: "{{ user }}" 
      comment: "{{ user_name }}" 
      group: "{{ user }}"
      password: "{{ password }}"
      update_password: on_create
